open-contracting/covid-19-procurement-explorer-admin

- covidadmin/settings.py
- covidadmin/urls.py
- requirements.txt
- vizualization/admin.py
- vizualization/apps.py
- vizualization/models.py
- vizualization/serializers.py
- vizualization/tests.py
- vizualization/urls.py
- vizualization/views.py
Visualization
-[x] total contracts api
-[x] total spendings api
-[x] country filter in total contracts and spending both api
-[x] total spendings api in usd amount format
> data vizualization

- vizualization/views.py
> [x] Added local info for spending

- vizualization/urls.py
- vizualization/views.py
[x] Local spending api updated
[x] changed date to month in key of object
> [x] Global Overview Api created

- vizualization/urls.py
- vizualization/views.py
[x] Added country wise api as well
> [x] Top supplier by value and number implemented

- vizualization/urls.py
- vizualization/views.py
[x] Bugs fixed for total_spending for before assignment error
> [x] Top-buyer api added

- vizualization/urls.py
- vizualization/views.py
-[x] Global page
-[x] Country page
> Direct, Open API

- vizualization/urls.py
- vizualization/views.py
[x] Status code wise grouped sum of contract value returned in contractstatus api
[x] Status code wise grouped total number of contracts returned in contractstatus api
> [x] ContractStatus api added

- vizualization/urls.py
- vizualization/views.py
-[x] Country page
-[x] Global page
> Quantity Correlation

- content/models.py
- covidadmin/settings.py
- requirements.txt
- vizualization/urls.py
- vizualization/views.py
-[x] Remove "_" and add "-" in API URL slug
-[x] Remove full name of country in API slug and add alpha 2 code
-[x] API response, removed local sum in global pages
-[x] Removed wagtailvideos from installed apps
> API code refactor

- vizualization/urls.py
- vizualization/views.py
[x] monopolization api implemented
[x] Code refactoring for average bids api
> [x] monopolization api implemented

- vizualization/urls.py
- vizualization/views.py
[x] changes necessary requirements from issue 38
> [x] Added new api for country map

- vizualization/urls.py
- vizualization/views.py
[x] Changed country-map-api to country-api and changed necessary bugs.
> [x] Added new api world-map

- content/models.py
- covidadmin/settings.py
- covidadmin/templates/content/events_page.html
- covidadmin/templates/content/insights_page.html
- covidadmin/templates/content/resources_page.html
- covidadmin/urls.py
-[x] Error in preview page fix
-[x] Added template to News/Blog page
-[x] Added template to Reports page
-[x] Added template to Events page
> CMS feedback issue #40

- content/admin.py
- content/models.py
-[x] Remove embed tag and add src tag to display in frontend
-[x] Remove body section from display list of events and resources page
> CMS fixes issue #40

- vizualization/views.py
[xTotal Income(Total Spendings)
[x]Total Contracts
[x]Direct / Open
[x]Top Buyers
[x]Tender Table
> Supplier Profile page implemented for these apis

- covidadmin/urls.py
- vizualization/views.py
[x] Country Map api should result an object of country detail; not an array
> [x] changed to correct spelling of `visualization` in api endpoints

- vizualization/urls.py
- vizualization/views.py
[x] Added a condition to exclude None category of goods_services_category
> [x] Product timeline implemented

- country/serializers.py
- country/urls.py
- country/views.py
[x] Suppliers table api added
[x] Filter added to these api
> [x] Buyers table api added

- vizualization/urls.py
- vizualization/views.py
[x] total of usd and local in total spending now fetched from goodsservices table
[x] country_tender table status changed to ‘canceled’
[x] Slight changes in query
> [x] Added new product timeline race api

- vizualization/urls.py
- vizualization/views.py
[x] condition for product-race
[x] hot fix
> [x] Buyers details api created

- country/serializers.py
- country/urls.py
- country/views.py
- vizualization/views.py
[x] Contract title preferably title. Check as %ilike% in contract title column
[x] Country code 2 character uppercase
[x] Buyer Id; database table primary key
[x] Supplier Id; database table primary key
[x] Product Id; database table primary key
[x] Contract method; procurement_procedure column in database table; consider the following value set
[x] Date range fields preferably as date_from and date_to. check with contract_date column
[x] Contract value USD comparison field, preferably as contract_value_usd amount value and value_comparison (string value either gt greater-than or lt less than)
[x] Country code changed to country code alpha2
> [x] Changed api endpoint to /api/v1/contracts/

- vizualization/urls.py
- vizualization/views.py
[x] Total number of buyers till data
[x] Difference percentage between last months and current month buyers count
[x] Month wise total number of unique suppliers
[x] Total number of suppliers till data
[x] Difference percentage between last months and current month supplier count
> [x] Month wise total number of unique buyers

- vizualization/views.py
[x] Removed - from relativedelta for world race map
> [x] Sanky for supplier and product code

- vizualization/urls.py
- vizualization/views.py
> [x] Added static buyers and suppliers api in filter parameters api

- country/serializers.py
- country/views.py
[x] Product categfory added on contracts api
> [x] Partial search on title

- country/serializers.py
- country/tasks.py
- country/views.py
- covidadmin/settings.py
- deploy.sh
- requirements.txt
- script.sh
- vizualization/views.py
[x] Filtering by equity_id is enabled in tender api
[x] limit, offset implemented in tender api
[x] fixed product_distribution api
[x] Worked on pagination error for country
[x] Country api fixed
[x] Product timeline race api fixed
[x] Deploy script added
[x] Page limit set to 20
[x] Added binary psycopg
[x] Limitpagination added i buyer and suplier
[x] Added supplier filter for product-timeline
> [x] Equity category added in tender contract api

- vizualization/views.py
[x] Query optimized for total-contracts api
[x] Code refactor for quantity correlation api
> [x] Query optimized and code refactored for total spending api

- country/management/commands/import_tender_excel.py
- country/models.py
- country/serializers.py
- country/tasks.py
- country/views.py
- covidadmin/settings.py
- vizualization/views.py
[x] Total spending api not including cancelled
[x] ordering changed to order
[x] contracts buyer supplier added ordering fields
[x] Sorting api changes buyer, supplier,contracts
[x] Ukraine data import
> [x] Ordering fixes

- vizualization/urls.py
- vizualization/views.py
[x] Api endpoint visualization/supplier-trend
[x] Api endpoint visualization/direct-open-contract-trend
> [x] Api endpoint visualization/buyer-trend

- vizualization/views.py
[x] Filter added on buyers and suppliers filter api
> [x] Global suppliers and country supplier fix

- country/management/commands/import_red_flag.py
- country/red_flag.py
- country/tasks.py
[x] Red flag import command edited
> [x] red flag implemented for 7 & 8

- country/management/commands/generate_country_contract_excel.py
- country/tasks.py
> 188-generate-contract-excel

- .github/workflows/lint.yml
- content/tests.py
- content/views.py
- country/tests.py
- vizualization/admin.py
- vizualization/tests.py
> ci: Add GitHub workflow for linting

- country/admin.py
- country/models.py
- country/serializers.py
- country/views.py
- requirements.in
- requirements.txt
> Removed annotate and red_flag details on Buyer / Supplier API

- country/admin.py
- country/tasks.py
- country/urls.py
- country/views.py
> CP-236 Country dataset delete functionality

- country/admin.py
- covidadmin/urls.py
-[x] change admin form of tender view
-[x] added goods and services table in tender view
-[x] added buyer table in tender admin
-[x] added supplier table in tender admin view
-[x] ordering of tender form fields fixed
-[x] unnecessary column hide in tender view
> edit-tender

- country/serializers.py
> Buyer, Supplier API

- .github/workflows/lint.yml
- requirements.in
- requirements.txt
- requirements_dev.txt
flower is not used by the app itself. It's a tool for sysadmins, so it ought to be managed in Salt.
> requirements: flower is now installed by deploy repo

- vizualization/views.py
> Average bid per contract API

- country/serializers.py
> country-api enhancement: api/v1/country

- country/admin.py
- country/serializers.py
> django country admin customization

- covidadmin/settings.py
- visualization/views.py
> CPA-261 Average calculation on visualization api

- visualization/views.py
> CPA-261-re Average calculation on visualization api

- covidadmin/settings.py
- visualization/helpers/general.py
- visualization/views.py
> 263-replace-cache-page-time-with-function

- country/management/commands/fill_contract_values.py
- country/management/commands/generate_excel_summary.py
- country/management/commands/import_red_flag.py
- country/management/commands/import_tender_from_id.py
- country/management/commands/process_currency_conversion.py
- country/management/commands/save_database_equity.py
> CPA-202 Use self.stdout/self.stderr instead of print()

- country/management/commands/generate_excel_summary.py
> Overall Summary Fix

- visualization/tests/test_urls.py
- visualization/tests/test_views.py
- visualization/urls.py
- visualization/views/__init__.py
- visualization/views/product_flow_view.py
- visualization/views/supplier_flow_view.py
> [x] Global supplier API solved

- country/admin.py
> CPA-257 Edit tender fixes

- country/tasks.py
[x] Redflag Concentration evaluation changed in tasks
> CPA-280 - Concentration Red Flag evaluation changed

- country/admin.py
> country filter in edit tender

- covidadmin/urls.py
> Remove live link

- country/admin.py
- country/management/commands/generate_country_contract_excel.py
- country/models.py
- country/tasks.py
> CPA-292 POST edit tasks

- country/management/commands/import_tender_from_id.py
- country/tests/commands/test_evaluate_contract_red_flag.py
- country/tests/commands/test_fill_contract_values.py
- country/tests/commands/test_generate_country_contract_excel.py
- country/tests/commands/test_generate_excel_summary.py
- country/tests/commands/test_import_tender_from_id.py
- country/tests/commands/test_process_currency_conversion.py
- country/tests/commands/test_save_database_equity.py
- country/tests/test_views.py
- country/views/delete_data_set_view.py
- covidadmin/middleware.py
- covidadmin/settings.py
- covidadmin/tests/test_views.py
- covidadmin/urls.py
- requirements.in
- requirements.txt
- requirements_dev.in
- requirements_dev.txt
> test-coverage-2021-05-05

- country/management/commands/save_database_equity.py
- country/tests/commands/test_evaluate_contract_red_flag.py
- country/tests/commands/test_fill_contract_values.py
- country/tests/commands/test_generate_excel_summary.py
- country/tests/commands/test_import_tender_from_id.py
- country/tests/commands/test_process_currency_conversion.py
- country/tests/commands/test_save_database_equity.py
> test-coverage-2021-05-06

- visualization/views/total_contracts_view.py
> 304-total-contracts-refactoring

- visualization/views/product_timeline_view.py
> 306 product-timeline-api- refactor

- visualization/views/quantity_correlation.py
> 312-quantity-correlation-refactor

- country/serializers.py
- country/tasks.py
- country/views/buyer_view.py
- country/views/supplier_view.py
- visualization/views/supplier_trend_view.py
- visualization/views/top_buyers.py
- visualization/views/top_suppliers.py
> CPA-309 Refactor Buyers/Suppliers API

- country/management/commands/generate_excel_summary.py
- country/management/commands/save_database_equity.py
> 314-overall-summary-add-columns

- visualization/views/quantity_correlation.py
> CPA-316 Contract correlation fix for global overview

- covidadmin/urls.py
- visualization/tests/test_urls.py
- visualization/views/__init__.py
- visualization/views/insights_view.py
> 307-insights-api-added

- country/management/commands/summarize_country_buyer.py
- country/management/commands/summarize_country_supplier.py
- country/tasks.py
- visualization/views/top_buyers.py
- visualization/views/top_suppliers.py
> CPA-322 Buyer / Supplier summary command issue

- country/admin.py
- country/serializers.py
- country/tests/test_views.py
- country/urls.py
- country/views/__init__.py
- country/views/country_detail_view.py
- country/views/country_view.py
- covidadmin/urls.py
- visualization/views/country_suppliers_view.py
- visualization/views/product_table_view.py
> API refactor

- content/signals.py
- country/admin.py
- country/apps.py
- country/signals.py
- country/tasks/__init__.py
- country/tasks/clear_cache_table.py
- country/tasks/delete_dataset.py
- country/tasks/import_contracts.py
- country/tasks/update_contract_attributes.py
- country/tasks/validate_and_store_contracts.py
- country/views/delete_data_set_view.py
- libraries/scheduler.py
> Fixes in data import
